version: '3.8'
services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: lole-gateway-mqtt
    ports:
      - "1883:1883"   # MQTT
      - "1884:1884"   # WebSocket
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped